apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-2
  labels:
    app: python-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-2
  template:
    metadata:
      labels:
        app: python-2
    spec:
      containers:
      - name: python-2
        image: 463932052716.dkr.ecr.eu-north-1.amazonaws.com/python-2:latest
        ports:
        - containerPort: 9091
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-2-service
spec:
  selector:
    app: python-2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
      nodePort: 30002
