apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-1
  template:
    metadata:
      labels:
        app: python-1
    spec:
      containers:
        - name: python-1
          image: 463932052716.dkr.ecr.eu-north-1.amazonaws.com/python-1:latest
          imagePullPolicy: Always   # 👈 force pulling new image every time
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: python-1-service
spec:
  type: NodePort
  selector:
    app: python-1
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30001
